Biblioteka2/Controllers/AuthorController.cs
using Domain.Interfaces;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Biblioteka2.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _uow;

        public AuthorController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public IActionResult Index()
        {
            var authors = _uow.Authors.GetAll();
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuthorId", "FirstName", "LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                await _uow.Authors.CreateAsync(author);
                if (await _uow.SaveAsync() > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(author);
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var author = await _uow.Authors.GetAsync((int)id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("AuthorId", "FirstName", "LastName")] Author author)
        {
            if (id != author.AuthorId)
            {
                return NotFound();
            }
            _uow.Authors.Update(author);
            if (await _uow.SaveAsync()>0)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _uow.Authors.GetAsync((int)id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            _uow.Authors.Delete(await _uow.Authors.GetAsync(id));
            await _uow.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Biblioteka2/Controllers/BookController.cs
using Domain.Interfaces;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace Biblioteka2.Controllers
{
    public class BookController : Controller
    {
        private readonly IUnitOfWork _uow;

        public BookController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public IActionResult Index()
        {
            var books = _uow.Books.GetAll();
            return View(books);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Book book;
            if (User != null && User.IsInRole("emp"))
            {
                book = await _uow.Books.GetBookAndItsReservationsAsync((int)id);
            }
            else
            {
                book = await _uow.Books.GetAsync((int)id);
            }

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [Authorize(Roles = "emp")]
        public IActionResult Create()
        {
            ViewData["Authors"] = new SelectList(_uow.Authors.GetAll(), "AuthorId", "FirstAndLastName");
            return View();
        }

        [Authorize(Roles = "emp")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId", "Name", "ReleaseDate", "AuthorId", "Description", "Quantity")] Book book)
        {
            if (ModelState.IsValid)
            {
                await _uow.Books.CreateAsync(book);
                if(await _uow.SaveAsync() > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["Authors"] = new SelectList(_uow.Authors.GetAll(), "AuthorId", "FirstAndLastName");
            return View(book);
        }

        [Authorize]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _uow.Books.GetAsync((int)id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["Authors"] = new SelectList(_uow.Authors.GetAll(), "AuthorId", "FirstAndLastName");
            return View(book);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("BookId", "Name", "ReleaseDate", "AuthorId", "Description", "Quantity")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            ViewData["Authors"] = new SelectList(_uow.Authors.GetAll(), "AuthorId", "FirstAndLastName");
            _uow.Books.Update(book);
            if (await _uow.SaveAsync() > 0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        [Authorize(Roles = "emp")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _uow.Books.GetAsync((int)id);
            if (id == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [Authorize(Roles = "emp")]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            _uow.Books.Delete(await _uow.Books.GetAsync(id));
            await _uow.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Biblioteka2/Controllers/ReservationController.cs
using Domain.Interfaces;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Biblioteka2.Controllers
{
    [Authorize]
    public class ReservationController : Controller
    {
        private readonly IUnitOfWork _uow;

        public ReservationController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public IActionResult Index()
        {
            if (User.IsInRole("emp"))
            {
                return View(_uow.Reservations.GetAll());
            }
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            return View(_uow.Reservations.GetUserReservations(userId));

        }

        public async Task<IActionResult> Reserve(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var book = await _uow.Books.GetAsync((int)id);
            if(book is null)
            {
                return NotFound();
            }
            var user = await _uow.Users.GetUserAsync(User);
            Reservation reservation = new()
            {
                Book = book,
                User = user,
            };
            if(await _uow.Reservations.MakeAsync(reservation))
            {
                await _uow.SaveAsync();
            }
            
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Retrive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var reservation = await _uow.Reservations.GetAsync((int)id);
            if(reservation is null)
            {
                return NotFound();
            }
            _uow.Reservations.Retrive(reservation);
            await _uow.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Biblioteka2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="Index">Książki</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Reservation" asp-action="Index">
                                    @(User.IsInRole("emp")?"Rezerwacje":"Moje rezerwacje")
                                </a>
                            </li>
                            @if (User.IsInRole("emp"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Author" asp-action="Index">
                                        Autorzy
                                    </a>
                                </li>
                            }

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2021 - Biblioteka
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>